import type { Metadata } from 'next'

import RootLayout from '@/core/layout/RootLayout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default RootLayout
